from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
        url(r'^$', 'animedbs.views.home'),
        url(r'^logout/$', 'animedbs.views.logout'),
        url(r'^user/$', 'animedbs.views.users'),
        url(r'^user/(\d+)/$', 'animedbs.views.user'),
        url(r'^profile/$', 'animedbs.views.profile'),
        url(r'^author/$', 'animedbs.views.authors'),
        url(r'^anime/$', 'animedbs.views.animes'),
        url(r'^anime/(\d+)/$', 'animedbs.views.anime'),
        url(r'^anime/(\d+)/image/$', 'animedbs.views.anime_images'),
        url(r'^anime/(\d+)/edit/image/$', 'animedbs.views.edit_anime_image'),
        url(r'^anime/(\d+)/edit/character/(.+)/$', 'animedbs.views.edit_anime_character'),
        url(r'^anime/(\d+)/new/character/$', 'animedbs.views.create_anime_character'),
        url(r'^anime/(\d+)/edit/character-image/(.+)/$', 'animedbs.views.edit_anime_character_image'),
        url(r'^anime/(\d+)/edit/$', 'animedbs.views.edit_anime'),
        url(r'^anime/new/$', 'animedbs.views.create_anime'),
        url(r'^season/$', 'animedbs.views.seasons'),
        url(r'^season/(\d+)/(\d+)/$', 'animedbs.views.season'),
        url(r'^anime/(\d+)/new/season/$', 'animedbs.views.create_season'),
        url(r'^season/(\d+)/(\d+)/edit/$', 'animedbs.views.edit_season'),
        url(r'^seiyu/$', 'animedbs.views.seiyus'),
        url(r'^seiyu/new/$', 'animedbs.views.create_seiyu'),
        url(r'^seiyu/(\d+)/$', 'animedbs.views.seiyu'),
        url(r'^seiyu/(\d+)/edit/$', 'animedbs.views.edit_seiyu'),
        url(r'^song/$', 'animedbs.views.songs'),
        url(r'^song/new/$', 'animedbs.views.create_song'),
        url(r'^song/(\d+)/$', 'animedbs.views.edit_song'),
        url(r'^song/(\d+)/edit/$', 'animedbs.views.edit_song'),
        url(r'^search/$', 'animedbs.views.search'),
        url(r'^comment/(\d+)/(\d+)/$', 'animedbs.views.comment'),
)
